#tomcat服务器配置 http://localhost:8080/ssms
server:
  address: localhost
  port: 8080
  
  
#字符编码设置
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    context-path: /crm3   #工程的站点根路径
      
#配置视图解析器的前缀和后缀

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  #配置数据源oracle数据库
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@42.51.78.5:1521:orcl
    username: CRM3
    password: scit_190506_crm3
    druid:
      #初始化连接大小
      initial-size: 3
      #最小空闲连接数
      min-idle: 2
      #最大连接数
      max-active: 20
      validationQuery: SELECT 1 FROM DUAL
      filters: stat
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-wait: 30000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
  
      
#加载mybatis配置文件
mybatis:
  config-location: classpath:conf.xml
